# Docs @ http://pre-commit.com/

default_language_version:
  python: "python3.12"
default_stages: ["commit", "push"]
minimum_pre_commit_version: "3.6.0"

# Intentionally running 'forbid-crlf' before 'trailing-whitespace'
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.4"
    hooks:
      - id: "forbid-crlf"
      - id: "forbid-tabs"

  - repo: https://github.com/timothycrosley/isort
    rev: "5.13.2"
    hooks:
      - id: "isort"
        types: ["python"]

  - repo: https://github.com/psf/black
    rev: "23.12.1"
    hooks:
      - id: "black"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: "check-added-large-files"
        args: ["--maxkb=500"]
      - id: "check-ast"
      - id: "check-builtin-literals"
      - id: "check-byte-order-marker"
      - id: "check-case-conflict"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
        exclude: ".devcontainer/.*"
      - id: "check-merge-conflict"
      - id: "check-symlinks"
      - id: "check-toml"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
        args: ["--unsafe"]
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "fix-encoding-pragma"
        args: ["--remove"]
      - id: "forbid-new-submodules"
      - id: "mixed-line-ending"
      - id: "trailing-whitespace"

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: "flake8"

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: "v1.0.6"
    hooks:
      - id: "shell-lint"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        args:
          - --config-file=mypy.ini
          - --pretty
        additional_dependencies: [
          "types-requests==2.31.0.20231231",
          "types-pytz==2024.1.0.20240203",
        ]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.1"
    hooks:
    -   id: poetry-check

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.27.3"
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
